### ISSUE TITLE
<TJSONRPCTcpIpClient> Sending Error JSON RPC id () : Error: Proof of work is higher than target payload 

### ISSUE THREAD

**Issue by tk-shockwave** [Vorksholk/PascalCoin-CUDA#3]
This error comes with each submitted share
<TJSONRPCTcpIpClient> Sending Error JSON RPC id () : Error: Proof of work is higher than target payload

**Comment by palginpav** [comment]
Proxy is broken, no target sent to miner, proxy sources included, maybe author will be able to do something with it.

[proxy.zip](https://github.com/Vorksholk/PascalCoin-CUDA/files/736237/proxy.zip)

**Comment by max-sanchez** [comment]
@tk-shockwave That's expected, the miner submits any share it finds if it fulfills a target of 24000000, which is almost 8192 times smaller than the current target.

@palginpav No target sent to miner? The miner doesn't need a target, it just uses 24000000. Is that the issue you're describing?

**Comment by palginpav** [comment]
So, this kind of error doesn't affect mining in general? I guess now I understand, sorry for bothering :)
