### ISSUE TITLE
Option to pass arguments to PascalProxyv2.jar

### ISSUE THREAD

**Issue by menacingm** [Vorksholk/PascalCoin-CUDA#8]
I'd like to set this up as a scheduled Windows Task. 

Is there a way to run the .jar file and pass the host, port, # of GPUs and Miner Name Prefix attributes in a single command?

**Comment by max-sanchez** [comment]
I have put up a new release with PascalProxyv3.jar inside, which allows you to pass in command line arguments for the host, port, number of GPUs to support, and miner prefix.

Thanks!
